#Rock Local Service, connect to ROCK_DEV env
server:
  port: ${SERVER_PORT:11003}

persistent:
  type: FILE
  folder: C:/Rock/Datas/Calypso/Persistence

local:
  file:
    root: C:/Rock/Datas/Calypso/Persistence/dataCenter